language: cpp

compiler:
  - gcc
  - clang

before_install:
  - sudo apt-get update
  - sudo apt-get install libsdl-mixer1.2-dev libsdl-gfx1.2-dev libsdl-image1.2-dev libboost-dev
  - ${CXX} --version
  - ${CC} --version
  - mkdir ~/dependency-prefix
  - export PKG_CONFIG_PATH=~/dependency-prefix/lib/pkgconfig

env:
  - BUILD_TYPE=Debug EXTRA_WARNING_FLAGS=""
  - BUILD_TYPE=Release EXTRA_WARNING_FLAGS=""
  - BUILD_TYPE=Debug EXTRA_WARNING_FLAGS="-Wall -Wextra"
  - BUILD_TYPE=Release EXTRA_WARNING_FLAGS="-Wall -Wextra"

install:
  - mkdir -p ./dependencies/
  - pushd ./dependencies/ && git clone https://github.com/jbeder/yaml-cpp.git && pushd yaml-cpp && git checkout release-0.5.1 && cmake -DCMAKE_INSTALL_PREFIX=~/dependency-prefix -DCMAKE_BUILD_TYPE="${BUILD_TYPE}" -DYAML_CPP_BUILD_CONTRIB=NO -DYAML_CPP_BUILD_TOOLS=NO . && make -j2 && make install && popd && popd

before_script:
  - cmake . -DCMAKE_BUILD_TYPE="${BUILD_TYPE}" -DYAMLCPP_INCLUDE_DIR=~/dependency-prefix/include -DCMAKE_CXX_FLAGS="${EXTRA_WARNING_FLAGS}" -DCMAKE_C_FLAGS="${EXTRA_WARNING_FLAGS}"

script: make -j2

os:
  - linux

